apiVersion: apps/v1
kind: Deployment
metadata:
  name: maven-sentry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: maven-sentry
  template:
    metadata:
      labels:
        app: maven-sentry
    spec:
      containers:
        - name: maven-sentry
          image: ghcr.io/your-org/maven-sentry:1.0.4
          ports:
            - containerPort: 8080
          env:
            - name: SENTRY_RELEASE
              value: "1.0.4"
