name: Build & Deploy

on:
  push:
    branches: [main]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  SENTRY_ORG: your-org
  SENTRY_PROJECT: maven-sentry
  SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Set release version from Git SHA
        run: echo "RELEASE_VERSION=maven-sentry-$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Build with Maven
        run: ./mvnw clean package -DskipTests

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Docker Image
        run: |
          docker build -t $REGISTRY/$IMAGE_NAME:${{ env.RELEASE_VERSION }} .

      - name: Push Docker Image
        run: |
          docker push $REGISTRY/$IMAGE_NAME:${{ env.RELEASE_VERSION }}

      - name: Upload Sentry release
        run: |
          curl -sL https://sentry.io/get-cli/ | bash
          export SENTRY_RELEASE=${{ env.RELEASE_VERSION }}
          ./sentry-cli releases new "$SENTRY_RELEASE"
          ./sentry-cli releases files "$SENTRY_RELEASE" upload-sourcemaps ./target
          ./sentry-cli releases finalize "$SENTRY_RELEASE"
